#!/usr/bin/env bash

# Install native apps
run_apps() {
	# utils
	utils=(1password spotify transmission vlc whatsapp telegram slack spectacle)

	# dev
	dev=(cyberduck docker github google-chrome firefox iterm2 postman visual-studio-code)
	
	for p in "${utils[@]} ${dev[@]}"; do
		brew cask install $p
	done
}
