#!/usr/bin/env bash

dotfiles=(.gitattributes .gitconfig .gitignore .osx .zshrc .vscode)

# Install dotfiles
run_dotfiles() {
	for i in "${dotfiles[@]}"; do
		if [[ "$i" == ".gitconfig" && -f ~/.gitconfig && "$USER" != "fabiomatavelli" ]]; then
			e_warning ".gitconfig already exists, do it manually"
		else
			rm -rf ~/$i
			ln -s .dotfiles/$i ~
		fi
	done

	if [ ! -d ~/Library/Application\ Support/Code/User ]; then
		mkdir -p ~/Library/Application\ Support/Code/User
	fi

	if [ ! -f ~/Library/Application\ Support/Code/User/settings.json ]; then
		ln -s ~/.vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
	fi
	
	source ~/.bash_profile
}
